### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by jamesbeltonIBM** [ibm-cloud-docs/atracker#2]
There are quite a few links in this page (https://cloud.ibm.com/docs/atracker?topic=atracker-cloud_services_other_ ) that don't lead to anything...

For example:

 see [IBM Cloud services that generate Activity Tracker events by location](https://cloud.ibm.com/activity-tracker?topic=activity-tracker-cloud_services_locations&interface=cli). leads to a 'it got cloudy in here / 404 page" 

and many of the location based event links go to a page that says "sorry this content isn't available"

**Comment by vanadiscrawford** [comment]
Thank you for bringing this to our attention.  All the links in this topic have been reviewed and corrected as required.
