### ISSUE TITLE
Minor typo in Getting started with IBM Cloud Activity Tracker Event Routing doc

### ISSUE THREAD

**Issue by jpapejr** [ibm-cloud-docs/atracker#3]
https://cloud.ibm.com/docs/atracker?topic=atracker-getting-started

First paragraph contains a capitalization typo: 

---

Use IBM Cloud® Activity Tracker Event Routing to configure how to route auditing events, both [global](https://cloud.ibm.com/docs/atracker?topic=atracker-event_types#event_types_global) and [location-based](https://cloud.ibm.com/docs/atracker?topic=atracker-event_types#event_types_location) event data, in your IBM Cloud. `a`uditing events are critical data for security operations and a key element for meeting compliance requirements. Control of the storage location is critical to building enterprise-grade solutions on the IBM Cloud.

Second sentence beginning with `auditing`, the `a` should be capitalized.

**Comment by vanadiscrawford** [comment]
Thanks for bringing this to our attention.  The error has been fixed and will show as updated in an hour or so.
