### ISSUE TITLE
Link "Viewing a target" on this page is broken

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/atracker#6]
Link "Viewing a target" on this page is broken
https://cloud.ibm.com/docs/atracker?topic=atracker-getting-started-target-logdna

```
To get the target definition in a region, see [Viewing a target](https://cloud.ibm.com/docs/atracker?topic=atracker-target#target-view).
```

**Comment by lopezdsr** [comment]
Thank you very much for your feedback. 
It has been fixed.
